name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check project files
        run: |
          test -f Dockerfile
          test -f docker-compose.yml
          test -f frontend/index.html
          test -f frontend/style.css
          test -f frontend/script.js

      - name: Build Docker image
        run: docker build -t ci-cd-demo:test .